data:
  root_dir: 'data'
  acdc_dir: 'ACDC'
  acdc_labels: 'ACDC/gt'
  acdc_images: 'ACDC/rgb_anon'
  bdd_dir: 'BDD'
  dawn_dir: 'DAWN'
  weather: ['fog', 'rain']
  image_size : [128, 128]

diffusion:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model:
  name: 'ddpm'
  im_channels : 3
  im_size : 128
  down_channels : [64, 128, 256, 512, 768] # should be changed
  mid_channels : [768, 768, 512]
  down_sample : [True, True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4
  attn_resolutions : [8, 16, 32, 64]

training:
  device: 'cuda'
  random_seed: 42
  epochs: 200
  batch_size: 4
  num_workers: 0
  lr: 0.0001
  log_interval: 10
  save_interval: 10
  sample_interval: 1000000000
  resume_training: False
  resume_checkpoint: ''
  sample_size: 2
  num_grid_rows : 1



folders:
  output: 'diffusion_model/outputs'
  weights: 'diffusion_model/weights'
  logs: 'diffusion_model/logs'
  checkpoints: 'diffusion_model/outputs/checkpoints'
  samples: 'diffusion_model/outputs/samples'